name = "api"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-06-09"
	
[vars]
REGION_NAME = '1'
SECRET_ACCESS_KEY = '2'
ACCESS_KEY_ID = '3'
ENDPOINT_URL = '4'
BUCKET_NAME = '5'