name = "api"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-06-09"
	
[vars]
REGION_NAME = 'iniregion'
SECRET_ACCESS_KEY = 'inisecret'
ACCESS_KEY_ID = 'iniaccess'
ENDPOINT_URL = 'iniendpoint'
BUCKET_NAME = 'inibucketname'