name = "api"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2023-06-09"


[vars]
REGION_NAME = ${{ secrets.REGION }}
SECRET_ACCESS_KEY = ${{ secrets.S3_SECRET_KEY }}
ACCESS_KEY_ID = ${{ secrets.S3_ACCESS_KEY }}
ENDPOINT_URL = ${{ secrets.S3_ENDPOINT_URL }}
ALT_ENDPOINT_URL = ${{ secrets.S3_API_TOKEN }}
BUCKET_NAME = ${{ secrets.S3_BUCKET_NAME }}