name = "api"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "${{secret.SECRET_KEY}}0${{secret.SECRET_KEY}}${{secret.ACCESS_KEY}}-06-09"


[vars]
REGION_NAME = '1'
SECRET_ACCESS_KEY = '${{secret.SECRET_KEY}}'
ACCESS_KEY_ID = '${{secret.ACCESS_KEY}}'
ENDPOINT_URL = '${{secret.ENDPOINT_URL}}'
BUCKET_NAME = '5'